### ISSUE TITLE
v3 spec

### ISSUE THREAD

**Issue by pan93412** [smhs-os-project/smhs-epf-faq#6]
預計暑假開始製作。

- React.js + TS
- New UI, to be simply.
- Cleanup the architect
- EPF Standard Article Format (EPF-SAF)
  ```yaml
  # 改自 https://epf.imych.one/doc/compress_pdf
  id: 我要怎麼幫 PDF 減肥？
  content:
    -
      stepTitle: 前提
      stepDesc: |
        可憐的教育部只給我們 2MB 的空間，而且還只能傳 PDF 呢！
        不過你知道你的 PDF 有 75% 以上都是 <b class='highlight'>垃圾資料</b>嗎？
        把垃圾資料刪掉就能縮小囉！
        Let's try it!
      stepPic:
        - https://epf.imych.one/assets/doc/compress/epfErrorFileLimit.gif
    -
      stepTitle: Step 1
      stepDesc: 去 Google 搜尋 <code><a class='is-blank'>ilovepdf</a></code>
      stepPic:
        - https://epf.imych.one/assets/doc/searchILovePDF.webp
    -
      stepTitle: Step 2
      stepDesc: |
        找到 ilovepdf 後點下去。
        你會看到一堆 PDF 工具，但我們今天是要找 <b class='highlight'>壓縮PDF</b>。
        找到之後按下去！！
      stepPic:
        - https://epf.imych.one/assets/doc/compress/epfPDFCompressS3.gif
  videos:
    -
      service: youtube_nocookie
      videoUrl: https://www.youtube-nocookie.com/embed/sdMU0srziN0
      width: 560
      height: 315
    -
      service: youtube_nocookie
      videoUrl: https://www.youtube-nocookie.com/embed/NwaKWYIiu1o
      width: 560
      height: 315
  ```
